language: python
python:
    - "2.7"

notifications:
    email: false

# Install dependencies
install: "pip install -r requirements.txt"

branches:
    only:
        - master

script: 
    - cd docs
    - make clean
    - make html
